## 1. Basic operations on matrices and vectors

In [1]:
import numpy as np

In [2]:
# 1.1 
def compute_vector_length(vector):
    len_of_vector = np.linalg.norm(vector)
    return len_of_vector

vector = np.array([1, 2, 3])
compute_vector_length(vector)

3.7416573867739413

In [3]:
# 1.2 
def compute_dot_product(vector1, vector2):
    dot_result = vector1.dot(vector2)
    return dot_result

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
compute_dot_product(vector1, vector2)

32

In [4]:
# 1.3
def matrix_multi_vector(matrix, vector):
    dot_matrix_vector = np.dot(matrix, vector)
    return dot_matrix_vector

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
vector = np.array([1, 2, 3])
matrix_multi_vector(matrix, vector)

array([14, 32])

In [5]:
# 1.4
def matrix_multi_matrix(matrix1, matrix2):
    mat_mul = np.matmul(matrix1, matrix2)
    return mat_mul

matrix1 = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
matrix2 = np.array([
    [2, 3],
    [4, 5],
    [6, 7]
])
matrix_multi_matrix(matrix1, matrix2)


array([[28, 34],
       [64, 79]])

In [6]:
# 1.5
def inverse_matrix(matrix):
    result = np.linalg.inv(matrix)
    return result

matrix = np.array([
    [1, 2],
    [3, 4]
])
inverse_matrix(matrix)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

Given a matrix $A \in \R^{2\times 2}$: 
$$
A = \begin{bmatrix}
-2 & 6\\
8 & -4
\end{bmatrix}
$$
We can find $A^{-1}$ by the following steps:
- Determinant: $det(A)=ad-bc=(-2)*(-4)-8*6=-40$
- $det(A)\ne 0$, then A is invertible
- Inverse matrix:
$$
A^{-1} = \frac{1}{det(A)} \begin{bmatrix}
-4 & -6\\
-8 & -2
\end{bmatrix} 
= \begin{bmatrix}
0.1 & 0.15\\
0.2 & 0.05
\end{bmatrix} 
$$


In [7]:
# We can check the result by using inverse function
matrix = np.array([
    [-2, 6],
    [8, -4]
])
inverse_matrix(matrix)

array([[0.1 , 0.15],
       [0.2 , 0.05]])

## 2. Eigenvector and Eigenvalue

Given matrix 
$$
A = \begin{bmatrix}
0.9 & 0.2\\
0.1 & 0.8
\end{bmatrix}
$$
- We can find the eigenvalue by using $det(A-\lambda I)=0$, then
$$
A-\lambda I = \begin{bmatrix}
0.9 & 0.2\\
0.1 & 0.8
\end{bmatrix}- \lambda \begin{bmatrix}
1 & 0\\
0 & 1
\end{bmatrix} = \begin{bmatrix}
0.9- \lambda & 0.2\\
0.1 & 0.8- \lambda
\end{bmatrix}
$$
Therefore, 
$$
det(A-\lambda I) = (0.9- \lambda)*(0.8- \lambda) - 0.1*0.2=\lambda^2-1.7\lambda+0.7=0
$$
$$
\implies \lambda = 1; \lambda = 0.7
$$
- Then, eigenvector: $Av=\lambda v \implies (A-\lambda I)v=0$. We set 2 cases:
Case 1: $\lambda = 1$
$$
(A-\lambda I)v=0 \implies \begin{bmatrix}
-0.1 & 0.2\\
0.1 & -0.2
\end{bmatrix} \begin{bmatrix}
x_1\\
x_2
\end{bmatrix} = 0 
$$
$$
\implies \begin{cases}
        -0.1x_1 + 0.2x_2=0\\
        0.1x_1 -0.2x_2=0
    \end{cases} \implies v = \begin{bmatrix}
2 \\
1
\end{bmatrix}
$$

Case 2: $\lambda = 0.7$
$$
(A-\lambda I)v=0 \implies \begin{bmatrix}
0.2 & 0.2\\
0.1 & 0.1
\end{bmatrix} \begin{bmatrix}
x_1\\
x_2
\end{bmatrix} = 0 
$$
$$
\implies \begin{cases}
        0.2x_1 + 0.2x_2=0\\
        0.1x_1 +0.1x_2=0
    \end{cases} \implies v = \begin{bmatrix}
1 \\
-1
\end{bmatrix}
$$

In [12]:
def compute_eigenvalues_eigenvectors(matrix):
    eigenvalues, eigenvectors = np.linalg.eig(matrix)
    return eigenvalues, eigenvectors

matrix = np.array([
    [0.9, 0.2],
    [0.1, 0.8]
])
eigval, eigvec = compute_eigenvalues_eigenvectors(matrix)
print(eigval)
print(eigvec)

[1.  0.7]
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


## 3. Cosine Similarity

Given 2 vectors
$$
x=\begin{bmatrix}
1\\ 2 \\3 \\4
\end{bmatrix}; y=\begin{bmatrix}
1\\ 0 \\3 \\0
\end{bmatrix} 
$$
The cosine similarity of x and y is:
$$
cos(x,y)=\frac{x\cdot y}{||x||\cdot ||y||}=\frac{1\times 1+2\times 0+3\times 3+4\times 0}{\sqrt{1^2+2^2+3^2+4^2}\times \sqrt{1^2+0^2+3^2+0^2}}=\frac{10}{10\sqrt{3}}=\frac{1}{\sqrt{3}}
$$

In [14]:
def compute_cosine(v1, v2):
    dot_product = compute_dot_product(v1, v2)
    vector1_norm = compute_vector_length(v1)
    vector2_norm = compute_vector_length(v2)
    return dot_product/(vector1_norm*vector2_norm)

x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
compute_cosine(x, y)

0.5773502691896257